#!/usr/bin/env python3
"""Prepare a deterministic, private W165 import batch.

The script deliberately keeps generated bytes outside Git.  Dry-run is the
default; --apply publishes an atomically-created batch directory.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
import tempfile
import zipfile
import zlib
from collections import Counter, defaultdict
from pathlib import Path, PurePosixPath
from typing import Any, BinaryIO

SHA256_HEX = 64
SAFE_HASH = set("0123456789abcdef")
JSON_FILES = ("alias-folds.json", "candidates.json", "cores.json", "sources.json")
ZIP_TIME = (1980, 1, 1, 0, 0, 0)
ZIP_COMPRESSLEVEL = 1
MAME2003_EPM_SHORTNAMES = frozenset({
    "avspa", "avspu", "ddtodh", "dino", "ecofghtru", "hsf2a",
    "mbomberj", "pzloop2", "pzloop2j",
})
PRODUCTION_CANDIDATE_CONTRACT_KIND = "hash-pinned-non-rom-candidate-ledger"
PRODUCTION_SOURCE_CONTRACT_KIND = "hash-pinned-authoritative-audit-inputs"
PRODUCTION_INVARIANTS = {
    "candidateRows": 656,
    "runtimeCoreScopedContracts": 655,
    "globalRawPayloadIdentities": 654,
    "relationTotals": {"parent": 227, "clone": 361, "hack": 4, "bootleg": 64},
    "thumbnailTotals": {"direct-or-alias": 463, "parent": 53, "source-reference": 140},
}
AUDITED_PYTHON_VERSION = (3, 12, 13)
AUDITED_PILLOW_VERSION = "12.3.0"
AUDITED_ZLIB_VERSION = "1.3.2"
AUDITED_LIBWEBP_VERSION = "1.6.0"


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
            size += len(chunk)
    return digest.hexdigest(), size


def assert_deterministic_runtime() -> None:
    if sys.version_info[:3] != AUDITED_PYTHON_VERSION:
        actual = ".".join(str(part) for part in sys.version_info[:3])
        expected = ".".join(str(part) for part in AUDITED_PYTHON_VERSION)
        raise RuntimeError(f"deterministic importer requires Python {expected}, got {actual}")
    runtime_zlib = getattr(zlib, "ZLIB_RUNTIME_VERSION", zlib.ZLIB_VERSION)
    if zlib.ZLIB_VERSION != AUDITED_ZLIB_VERSION or runtime_zlib != AUDITED_ZLIB_VERSION:
        raise RuntimeError(
            f"deterministic importer requires zlib {AUDITED_ZLIB_VERSION}, "
            f"got compile={zlib.ZLIB_VERSION} runtime={runtime_zlib}"
        )
    try:
        import PIL
        from PIL import features
    except ImportError as error:
        raise RuntimeError("deterministic importer requires Pillow with WebP support") from error
    if PIL.__version__ != AUDITED_PILLOW_VERSION:
        raise RuntimeError(f"deterministic importer requires Pillow {AUDITED_PILLOW_VERSION}, got {PIL.__version__}")
    libwebp = features.version_module("webp") if features.check("webp") else None
    if libwebp != AUDITED_LIBWEBP_VERSION:
        raise RuntimeError(f"deterministic importer requires libwebp {AUDITED_LIBWEBP_VERSION}, got {libwebp or 'unavailable'}")


def require_hash(value: Any, field: str) -> str:
    if not isinstance(value, str) or len(value) != SHA256_HEX or any(c not in SAFE_HASH for c in value.lower()):
        raise ValueError(f"{field} must be a 64-character SHA-256 hex string")
    return value.lower()


def safe_relative(value: str, field: str = "path") -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty relative path")
    if "\\" in value or value.startswith("/") or (len(value) > 1 and value[1] == ":"):
        raise ValueError(f"{field} must use a relative POSIX path")
    path = PurePosixPath(value)
    if path.is_absolute() or any(part in ("", ".", "..") for part in path.parts):
        raise ValueError(f"{field} contains traversal or ambiguous segments")
    return "/".join(path.parts)


def safe_zip_member(value: str) -> str:
    # ZIP names are allowed to contain spaces and Unicode, but not alternate
    # separators or a path that could escape the extraction boundary.
    return safe_relative(value.replace("/", "/"), "ZIP member")


def ensure_regular(path: Path, label: str) -> None:
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"{label} must be a regular non-symlink file: {path}")


def assert_production_contract(candidates: dict[str, Any], sources: dict[str, Any]) -> bool:
    candidate_contract = candidates.get("contractKind") == PRODUCTION_CANDIDATE_CONTRACT_KIND
    source_contract = sources.get("contractKind") == PRODUCTION_SOURCE_CONTRACT_KIND
    if candidate_contract != source_contract:
        raise ValueError("production candidate and source contract kinds must be paired")
    if not candidate_contract:
        return False

    rows = candidates.get("rows")
    if not isinstance(rows, list) or len(rows) != PRODUCTION_INVARIANTS["candidateRows"]:
        actual = len(rows) if isinstance(rows, list) else "invalid"
        raise ValueError(f"production candidate ledger must contain exactly 656 rows, got {actual}")
    if sources.get("invariants") != PRODUCTION_INVARIANTS:
        raise ValueError("production source invariants differ from the frozen 656/655/654 contract")

    computed = {
        "runtimeCoreScopedContracts": len({row.get("runtimeContractFingerprint") for row in rows}),
        "globalRawPayloadIdentities": len({row.get("rawContentContractSha256") for row in rows}),
        "relationTotals": dict(Counter(str(row.get("relationKind")) for row in rows)),
        "thumbnailTotals": dict(Counter(str((row.get("thumbnail") or {}).get("matchKind")) for row in rows)),
    }
    for field, expected in PRODUCTION_INVARIANTS.items():
        if field == "candidateRows":
            continue
        if computed[field] != expected:
            raise ValueError(f"production candidate ledger invariant mismatch at {field}")
    return True


def load_contracts(contracts_dir: Path) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any], dict[str, Any], dict[str, str]]:
    sums_path = contracts_dir / "SHA256SUMS.txt"
    ensure_regular(sums_path, "SHA256SUMS.txt")
    expected: dict[str, str] = {}
    for line in sums_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            raise ValueError("SHA256SUMS.txt contains a malformed line")
        expected[parts[1]] = require_hash(parts[0], f"SHA256SUMS {parts[1]}")
    if set(expected) != set(JSON_FILES):
        raise ValueError("SHA256SUMS.txt must cover exactly the four contract JSON files")
    loaded: dict[str, dict[str, Any]] = {}
    for name in JSON_FILES:
        path = contracts_dir / name
        ensure_regular(path, name)
        actual, _ = sha256_file(path)
        if actual != expected[name]:
            raise ValueError(f"contract hash mismatch for {name}: expected {expected[name]}, got {actual}")
        loaded[name] = json.loads(path.read_text(encoding="utf-8"))
    assert_production_contract(loaded["candidates.json"], loaded["sources.json"])
    return loaded["candidates.json"], loaded["cores.json"], loaded["sources.json"], loaded["alias-folds.json"], expected


def source_category(relative: str) -> str:
    lower = relative.lower()
    if lower.endswith(".zip") and (lower.endswith("/neogeo.zip") or lower == "uni-bios.zip"):
        return "bios_archive"
    if lower.startswith("roms/") and lower.endswith(".zip"):
        return "rom_archive"
    if lower.startswith("sshots/"):
        return "screenshot"
    if lower.startswith("eeprom/") or lower.startswith("saves/"):
        return "save_sample"
    return "auxiliary"


class SourcePool:
    def __init__(self, source_root: Path):
        self.source_root = source_root.resolve()
        self.entries: dict[tuple[int, str], list[tuple[Path, str]]] = defaultdict(list)
        self._resolved: dict[tuple[int, str], tuple[Path, str, str]] = {}
        self.zip_paths: list[Path] = []
        self._build_index()

    def _build_index(self) -> None:
        rom_root = self.source_root / "roms"
        if not rom_root.is_dir():
            raise ValueError(f"source root lacks roms directory: {rom_root}")
        for path in sorted(rom_root.rglob("*.zip"), key=lambda p: p.as_posix().lower()):
            ensure_regular(path, "ROM source archive")
            self.zip_paths.append(path)
            with zipfile.ZipFile(path) as archive:
                seen_names: set[str] = set()
                for info in archive.infolist():
                    if info.is_dir():
                        continue
                    name = safe_zip_member(info.filename)
                    if name in seen_names:
                        raise ValueError(f"duplicate ZIP member {name} in {path}")
                    seen_names.add(name)
                    key = (int(info.file_size), f"{info.CRC:08x}")
                    self.entries[key].append((path, name))

    def get(self, size: int, crc: str) -> tuple[bytes, str, str]:
        key = (int(size), str(crc).lower().zfill(8))
        matches = self.entries.get(key, [])
        if not matches:
            raise ValueError(f"no source member matches size={size} crc={key[1]}")
        resolved = self._resolved.get(key)
        if resolved is None:
            by_hash: dict[str, tuple[Path, str]] = {}
            for archive_path, name in sorted(matches, key=lambda item: (item[0].as_posix().lower(), item[1])):
                with zipfile.ZipFile(archive_path) as archive:
                    data = archive.read(name)
                by_hash.setdefault(sha256_bytes(data), (archive_path, name))
            if len(by_hash) != 1:
                raise ValueError(f"ambiguous source member size={size} crc={key[1]} has {len(by_hash)} payload hashes")
            digest, (archive_path, name) = sorted(by_hash.items())[0]
            resolved = (archive_path, name, digest)
            self._resolved[key] = resolved
        archive_path, name, digest = resolved
        with zipfile.ZipFile(archive_path) as archive:
            data = archive.read(name)
        if len(data) != int(size) or f"{zipfile.crc32(data) & 0xffffffff:08x}" != key[1]:
            raise ValueError(f"source member verification failed for {archive_path}!{name}")
        return data, digest, f"{archive_path.relative_to(self.source_root).as_posix()}!{name}"


def deterministic_zip(members: list[tuple[str, bytes]]) -> BinaryIO:
    output = tempfile.SpooledTemporaryFile(max_size=16 * 1024 * 1024)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=ZIP_COMPRESSLEVEL) as archive:
        archive.comment = b""
        for name, data in sorted(members, key=lambda pair: pair[0]):
            info = zipfile.ZipInfo(filename=name, date_time=ZIP_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.create_system = 3
            info.external_attr = (0o100644 << 16)
            info.extra = b""
            info.comment = b""
            info.flag_bits |= 0x800
            archive.writestr(info, data, compress_type=zipfile.ZIP_DEFLATED, compresslevel=ZIP_COMPRESSLEVEL)
    output.seek(0)
    return output


def sha256_stream(stream: BinaryIO) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    stream.seek(0)
    while True:
        chunk = stream.read(1024 * 1024)
        if not chunk:
            break
        digest.update(chunk)
        size += len(chunk)
    stream.seek(0)
    return digest.hexdigest(), size


class GeneratedOutput:
    def __init__(self, root: Path | None):
        self.root = root
        self.paths: set[str] = set()

    def _target(self, relative: str) -> Path | None:
        normalized = safe_relative(relative, "generated path")
        if self.root is None:
            return None
        return self.root / Path(*normalized.split("/"))

    def put_bytes(self, relative: str, data: bytes) -> None:
        target = self._target(relative)
        if relative in self.paths:
            return
        self.paths.add(relative)
        if target is None:
            return
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)

    def put_stream(self, relative: str, stream: BinaryIO) -> None:
        target = self._target(relative)
        if relative in self.paths:
            return
        self.paths.add(relative)
        if target is None:
            return
        target.parent.mkdir(parents=True, exist_ok=True)
        stream.seek(0)
        with target.open("xb") as handle:
            shutil.copyfileobj(stream, handle, length=1024 * 1024)
        stream.seek(0)


def thumbnail_match_kind(row: dict[str, Any]) -> str:
    thumb = row.get("thumbnail") or {}
    kind = str(thumb.get("matchKind") or "")
    if kind == "parent":
        return "parent"
    if kind == "source-reference":
        return "source_reference"
    evidence = str(thumb.get("evidence") or "").lower()
    return "alias" if "alias" in evidence else "exact"


def find_screenshots(source_root: Path) -> dict[str, Path]:
    directory = source_root / "sshots"
    result: dict[str, Path] = {}
    priority = {".bmp": 0, ".png": 1, ".jpg": 2, ".jpeg": 3, ".webp": 4}
    if not directory.is_dir():
        return result
    for path in sorted(directory.iterdir(), key=lambda p: (p.name.casefold(), p.name)):
        if not path.is_file() or path.is_symlink():
            continue
        if path.suffix.lower() not in priority:
            continue
        key = path.stem.casefold()
        if key not in result or priority.get(path.suffix.lower(), 99) < priority.get(result[key].suffix.lower(), 99):
            result[key] = path
    return result


def convert_thumbnail(source: Path) -> bytes:
    try:
        from PIL import Image
    except ImportError as error:
        raise RuntimeError("thumbnail conversion requires Pillow; run with the pinned arcade-import Python runtime") from error
    with Image.open(source) as image:
        image = image.convert("RGB")
        output = tempfile.SpooledTemporaryFile(max_size=2 * 1024 * 1024)
        image.save(output, format="WEBP", quality=80, method=6)
        output.seek(0)
        return output.read()


def relative_files(source_root: Path) -> list[Path]:
    return sorted((path for path in source_root.rglob("*") if path.is_file() and not path.is_symlink()), key=lambda p: p.relative_to(source_root).as_posix())


def source_inventory(source_root: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for path in relative_files(source_root):
        rel = path.relative_to(source_root).as_posix()
        digest, size = sha256_file(path)
        rows.append({"path": rel, "sha256": digest, "fileSize": size, "category": source_category(rel)})
    return rows


def decode_kawaks_srm(data: bytes) -> bytes:
    if len(data) < 4:
        raise ValueError("Kawaks SRAM is shorter than its four-byte header")
    payload_size = int.from_bytes(data[:4], "little")
    payload = data[4:]
    if payload_size != len(payload):
        raise ValueError(f"Kawaks SRAM payload length mismatch: expected {payload_size}, got {len(payload)}")
    decoded = bytearray()
    index = 0
    while index < len(payload):
        opcode = payload[index]
        index += 1
        if opcode <= 0xBF:
            decoded.append(opcode)
            continue
        if index >= len(payload):
            raise ValueError("Kawaks SRAM repeat opcode lacks a value byte")
        decoded.extend([payload[index]] * (opcode - 0xC0))
        index += 1
        if len(decoded) > 65_536:
            raise ValueError("Kawaks SRAM expands beyond 65,536 bytes")
    if len(decoded) != 65_536:
        raise ValueError(f"Kawaks SRAM decodes to {len(decoded)} bytes instead of 65,536")
    return bytes(decoded)


def build_save_sample_evidence(
    source_root: Path,
    auxiliary: list[dict[str, Any]],
    candidate_rows: list[dict[str, Any]],
    core_rows: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    core_name_by_id = {
        str(core_id): str(core.get("coreName") or "").casefold()
        for core_id, core in core_rows.items()
    }
    fbneo_targets: dict[str, set[str]] = defaultdict(set)
    for row in candidate_rows:
        core_id = str(row.get("coreArtifactId") or "")
        if core_name_by_id.get(core_id) == "fbneo":
            fbneo_targets[str(row.get("setName") or "").casefold()].add(core_id)
    core_ids_by_name: dict[str, set[str]] = defaultdict(set)
    for core_id, core in core_rows.items():
        core_ids_by_name[str(core.get("coreName") or "").casefold()].add(str(core_id))

    def unique_core_id(core_name: str) -> str:
        matches = sorted(core_ids_by_name.get(core_name, set()))
        if len(matches) != 1:
            raise ValueError(f"save evidence requires exactly one {core_name} core artifact, got {len(matches)}")
        return matches[0]

    mame_core_id: str | None = None
    records: list[dict[str, Any]] = []
    for evidence in auxiliary:
        if evidence.get("category") != "save_sample":
            continue
        source_path = str(evidence["path"])
        suffix = PurePosixPath(source_path).suffix.casefold()
        if suffix not in (".epm", ".srm"):
            raise ValueError(f"unsupported save sample extension: {source_path}")
        shortname = PurePosixPath(source_path).stem.casefold()
        source_bytes = (source_root / Path(*source_path.split("/"))).read_bytes()
        if len(source_bytes) != evidence["fileSize"] or sha256_bytes(source_bytes) != evidence["sha256"]:
            raise ValueError(f"save sample source evidence changed while preparing: {source_path}")

        if suffix == ".epm":
            if len(source_bytes) != 128:
                raise ValueError(f"raw MAME EEPROM must be exactly 128 bytes: {source_path}")
            if mame_core_id is None:
                mame_core_id = unique_core_id("mame2003_plus")
            decoded = source_bytes
            format_name = "mame2003-plus-raw-eeprom-v1"
            target_core_name = "mame2003_plus"
            target_core_ids = {mame_core_id} if shortname in MAME2003_EPM_SHORTNAMES else set()
            target_extension = "nv"
            unmapped_reason = "no exact audited MAME2003-Plus shortname mapping"
        else:
            decoded = decode_kawaks_srm(source_bytes)
            format_name = "kawaks-srm-rle-v1"
            target_core_name = "fbneo"
            target_core_ids = fbneo_targets.get(shortname, set())
            target_extension = "fs"
            unmapped_reason = "no exact bundled FBNeo driver shortname mapping; candidate generation is forbidden"

        decoded_sha = sha256_bytes(decoded)
        exact_mapping = len(target_core_ids) == 1
        if len(target_core_ids) > 1:
            raise ValueError(f"ambiguous exact save target for {source_path}: {sorted(target_core_ids)}")
        candidate_target = None
        if exact_mapping:
            target_core_id = next(iter(target_core_ids))
            candidate_target = {
                "coreArtifactId": target_core_id,
                "coreName": target_core_name,
                "fileName": f"{shortname}.{target_extension}",
                "sha256": decoded_sha,
                "fileSize": len(decoded),
            }

        records.append({
            **evidence,
            "format": format_name,
            "shortname": shortname,
            "semanticSampleId": f"{format_name}:{shortname}",
            "decodedSha256": decoded_sha,
            "decodedSize": len(decoded),
            "mappingState": "exact" if exact_mapping else "unmapped",
            "candidateTarget": candidate_target,
            "runtimeVerified": False,
            "archivalOnly": True,
            "runtimeWriteAllowed": False,
            "independentRuntimeVerificationRequired": exact_mapping,
            "reason": None if exact_mapping else unmapped_reason,
        })
    return sorted(records, key=lambda row: row["path"])


def render_report(manifest: dict[str, Any]) -> str:
    summary = manifest.get("summary", {})
    resolution_counts = Counter(row.get("state") for row in manifest.get("candidateResolutions", []))
    lines = [
        f"# W165 Import Batch {manifest.get('batchId')}",
        "",
        f"Manifest SHA-256: `{manifest.get('manifestSha256')}`",
        f"Cold source SHA-256: `{(manifest.get('coldSource') or {}).get('sha256')}`",
        "",
        "## Summary",
        "",
        f"- Candidate rows: {summary.get('candidateRows', 0)}",
        f"- Generated archives: {summary.get('generatedArchiveCount', 0)}",
        f"- Thumbnail source basenames: {summary.get('thumbnailSourceBasenames', 0)}",
        f"- Extracted source files: {summary.get('sourceFiles', 0)}",
        f"- Extracted source bytes: {summary.get('sourceBytes', 0)}",
        "",
        "## Candidate Resolutions",
        "",
    ]
    for state in ("ready", "unverified", "blocked", "unsupported"):
        lines.append(f"- {state}: {resolution_counts.get(state, 0)}")
    lines.extend(["", "## Archival NVRAM Evidence", "", "| Source | Format | Candidate target | Mapping | Runtime verified |", "| --- | --- | --- | --- | --- |"])
    for row in manifest.get("saveSampleEvidence", []):
        target = (row.get("candidateTarget") or {}).get("fileName") or "none"
        lines.append(f"| `{row.get('path')}` | `{row.get('format')}` | `{target}` | {row.get('mappingState')} | no |")
    lines.extend(["", "Decoded bytes are recorded by hash only. No .fs or .nv file is written into the batch or a runtime save directory.", ""])
    return "\n".join(lines)


def build_manifest(args: argparse.Namespace, generated_root: Path | None = None) -> dict[str, Any]:
    assert_deterministic_runtime()
    source_root = Path(args.source_root).resolve()
    cold_source = Path(args.cold_source).resolve()
    contracts_dir = Path(args.contracts_dir).resolve()
    if not source_root.is_dir():
        raise ValueError(f"source root is not a directory: {source_root}")
    ensure_regular(cold_source, "cold source")
    candidates, cores, sources, alias_folds, contract_hashes = load_contracts(contracts_dir)
    rows = candidates.get("rows")
    if not isinstance(rows, list):
        raise ValueError("candidates.json rows must be an array")
    core_rows = {row.get("id"): row for row in cores.get("cores", [])}
    pool = SourcePool(source_root)
    screenshots = find_screenshots(source_root)
    cold_sha, cold_size = sha256_file(cold_source)
    batch_id = args.batch_id or f"w165-{cold_sha[:16]}"
    safe_relative(batch_id, "batch-id")

    by_core_set = {(row.get("coreArtifactId"), row.get("setName")): row for row in rows}
    archives: list[dict[str, Any]] = []
    resolutions: list[dict[str, Any]] = []
    thumbnail_records: dict[str, dict[str, Any]] = {}
    thumbnail_sources: dict[str, dict[str, Any]] = {}
    generated = GeneratedOutput(generated_root)
    for basename, image_source in screenshots.items():
        source_sha, source_size = sha256_file(image_source)
        image_bytes = convert_thumbnail(image_source)
        image_sha = sha256_bytes(image_bytes)
        image_rel = f"thumbnails/sha256/{image_sha[:2]}/{image_sha}.webp"
        generated.put_bytes(image_rel, image_bytes)
        thumbnail_sources[basename] = {
            "sourcePath": image_source.relative_to(source_root).as_posix(),
            "sourceFileSha256": source_sha,
            "sourceFileSize": source_size,
            "assetPath": image_rel,
            "sha256": image_sha,
            "fileSize": len(image_bytes),
        }

    for row in rows:
        candidate_id = str(row.get("id"))
        errors: list[str] = []
        member_data: list[tuple[str, bytes, str, str, str]] = []
        for member in row.get("members", []):
            if not isinstance(member, list) or len(member) != 3:
                errors.append("malformed member contract")
                continue
            name, size, crc = member
            try:
                safe_zip_member(str(name))
                data, digest, source_path = pool.get(int(size), str(crc))
                member_data.append((str(name), data, digest, source_path, str(crc).lower().zfill(8)))
            except (ValueError, KeyError, zipfile.BadZipFile) as error:
                errors.append(str(error))

        parent = None
        parent_member_keys: set[tuple[str, int, str]] = set()
        if row.get("archiveLayout") == "split":
            parent = by_core_set.get((row.get("coreArtifactId"), row.get("runtimeParentSetName")))
            if not parent:
                errors.append("split candidate has no same-core runtime parent")
            else:
                parent_member_keys = {
                    (str(member[0]), int(member[1]), str(member[2]).lower().zfill(8))
                    for member in parent.get("members", [])
                }
                if not parent_member_keys:
                    errors.append("split parent has no members")
        output_members = [
            item for item in member_data
            if (item[0], len(item[1]), item[4]) not in parent_member_keys
        ]
        if row.get("archiveLayout") == "standalone":
            output_members = member_data
        archive_rel = f"archives/{str(row.get('coreArtifactId'))}/{str(row.get('setName'))}.zip"
        mounts = []
        if parent:
            mounts.append({"role": "parent", "candidateId": str(parent.get("id")), "path": f"archives/{parent.get('coreArtifactId')}/{parent.get('setName')}.zip"})
        mounts.append({"role": "primary", "candidateId": candidate_id, "path": archive_rel})
        archive_stream = deterministic_zip([(name, data) for name, data, *_ in output_members]) if not errors else None
        archive_sha, archive_size = sha256_stream(archive_stream) if archive_stream else (None, 0)
        archive_record = {
            "candidateId": candidate_id,
            "coreArtifactId": row.get("coreArtifactId"),
            "setName": row.get("setName"),
            "title": row.get("title"),
            "platform": str(row.get("platform") or "arcade").lower(),
            "relationKind": row.get("relationKind"),
            "datParentSetName": row.get("datParentSetName"),
            "familyRootSetName": row.get("runtimeParentSetName") or row.get("datParentSetName") or row.get("setName"),
            "archiveLayout": row.get("archiveLayout"),
            "archivePath": archive_rel,
            "archiveSha256": archive_sha,
            "archiveSize": archive_size,
            "mounts": mounts,
            "members": [
                {"name": name, "size": len(data), "crc32": crc, "sha256": digest, "sourcePath": source_path}
                for name, data, digest, source_path, crc in sorted(output_members, key=lambda item: item[0])
            ],
        }
        archives.append(archive_record)
        if archive_stream:
            try:
                generated.put_stream(archive_rel, archive_stream)
            finally:
                archive_stream.close()
        thumb = row.get("thumbnail") or {}
        source_set = str(thumb.get("sourceSetName") or row.get("setName") or "").casefold()
        thumbnail_source = thumbnail_sources.get(source_set)
        thumb_record = {
            "candidateId": candidate_id,
            "sourceSetName": source_set,
            "matchKind": thumbnail_match_kind(row),
            "sourcePath": thumbnail_source["sourcePath"] if thumbnail_source else None,
            "sourceFileSha256": thumbnail_source["sourceFileSha256"] if thumbnail_source else None,
            "sourceFileSize": thumbnail_source["sourceFileSize"] if thumbnail_source else 0,
            "assetPath": None,
            "sha256": None,
            "fileSize": 0,
        }
        if not thumbnail_source:
            errors.append(f"thumbnail source basename not found: {source_set}")
        else:
            thumb_record.update({
                "assetPath": thumbnail_source["assetPath"],
                "sha256": thumbnail_source["sha256"],
                "fileSize": thumbnail_source["fileSize"],
            })
        thumbnail_records[candidate_id] = thumb_record
        resolutions.append({
            "candidateId": candidate_id,
            "runtimeContractFingerprint": row.get("runtimeContractFingerprint"),
            "rawContentContractSha256": row.get("rawContentContractSha256"),
            "state": "blocked" if errors else "unverified",
            "reasons": sorted(set(errors)),
        })

    # Include every cold-extract file as private evidence. Decoded save data is
    # represented by hashes and candidate filenames only; it is never emitted.
    auxiliary = source_inventory(source_root)
    save_samples = build_save_sample_evidence(source_root, auxiliary, rows, core_rows)
    source_categories = Counter(row["category"] for row in auxiliary)
    source_inventory_sha = sha256_bytes(canonical_json(auxiliary).encode("utf-8"))

    thumbnail_counts = Counter(record["matchKind"] for record in thumbnail_records.values())
    relation_counts = Counter(str(row.get("relationKind")) for row in rows)
    layout_counts = Counter(str(row.get("archiveLayout")) for row in rows)
    manifest: dict[str, Any] = {
        "schemaVersion": 1,
        "kind": "w165-import-batch-v1",
        "batchId": batch_id,
        "coldSource": {"sha256": cold_sha, "fileSize": cold_size},
        "contracts": {
            "sha256sumsSha256": sha256_file(contracts_dir / "SHA256SUMS.txt")[0],
            **{name.removesuffix(".json") + "Sha256": digest for name, digest in sorted(contract_hashes.items())},
        },
        "cores": sorted(core_rows.values(), key=lambda row: str(row.get("id"))),
        "candidateResolutions": sorted(resolutions, key=lambda row: row["candidateId"]),
        "archives": sorted(archives, key=lambda row: row["candidateId"]),
        "thumbnails": sorted(thumbnail_records.values(), key=lambda row: row["candidateId"]),
        "thumbnailSources": sorted(({"basename": key, **value} for key, value in thumbnail_sources.items()), key=lambda row: row["basename"]),
        "auxiliaryEvidence": auxiliary,
        "saveSampleEvidence": save_samples,
        "sourceInventory": {
            "sha256": source_inventory_sha,
            "fileCount": len(auxiliary),
            "totalBytes": sum(row["fileSize"] for row in auxiliary),
        },
        "summary": {
            "candidateRows": len(rows),
            "runtimeCoreScopedContracts": len({row.get("runtimeContractFingerprint") for row in rows}),
            "globalRawPayloadIdentities": len({row.get("rawContentContractSha256") for row in rows}),
            "relationKinds": dict(sorted(relation_counts.items())),
            "archiveLayouts": dict(sorted(layout_counts.items())),
            "coreIds": sorted({str(row.get("coreArtifactId")) for row in rows}),
            "thumbnailMatchKinds": dict(sorted(thumbnail_counts.items())),
            "thumbnailSourceBasenames": len(thumbnail_sources),
            "thumbnailUniqueObjects": len({row["sha256"] for row in thumbnail_sources.values()}),
            "generatedArchiveCount": len([path for path in generated.paths if path.startswith("archives/")]),
            "sourceFiles": len(auxiliary),
            "sourceBytes": sum(row["fileSize"] for row in auxiliary),
            "sourceCategories": dict(sorted(source_categories.items())),
            "saveSampleFormats": dict(sorted(Counter(row["format"] for row in save_samples).items())),
            "saveSampleMappings": dict(sorted(Counter(row["mappingState"] for row in save_samples).items())),
        },
    }
    digest = sha256_bytes(canonical_json(manifest).encode("utf-8"))
    manifest["manifestSha256"] = digest
    return {"manifest": manifest}


def existing_batch_asset(output_dir: Path, relative: str) -> Path:
    normalized = safe_relative(relative, "existing batch asset path")
    target = output_dir / Path(*normalized.split("/"))
    if target.is_symlink() or not target.is_file():
        raise ValueError(f"existing batch asset is missing or unsafe: {normalized}")
    resolved = target.resolve()
    if resolved != output_dir and output_dir not in resolved.parents:
        raise ValueError(f"existing batch asset escapes output directory: {normalized}")
    return target


def assert_existing_batch_integrity(output_dir: Path, manifest: dict[str, Any]) -> None:
    expected_manifest = canonical_json(manifest) + "\n"
    manifest_path = existing_batch_asset(output_dir, "manifest.json")
    if manifest_path.read_text(encoding="utf-8") != expected_manifest:
        raise ValueError("existing batch output has a missing or mismatched manifest.json")

    report_path = existing_batch_asset(output_dir, "report.md")
    if report_path.read_text(encoding="utf-8") != render_report(manifest):
        raise ValueError("existing batch output has a missing or mismatched report.md")

    assets: dict[str, tuple[str, int]] = {}
    for archive in manifest.get("archives", []):
        digest = archive.get("archiveSha256")
        if digest is None:
            continue
        relative = safe_relative(archive.get("archivePath"), "archive path")
        assets[relative] = (
            require_hash(digest, f"archive SHA-256 for {relative}"),
            int(archive.get("archiveSize")),
        )
    for thumbnail in manifest.get("thumbnailSources", []):
        relative = safe_relative(thumbnail.get("assetPath"), "thumbnail asset path")
        expected = (
            require_hash(thumbnail.get("sha256"), f"thumbnail SHA-256 for {relative}"),
            int(thumbnail.get("fileSize")),
        )
        previous = assets.setdefault(relative, expected)
        if previous != expected:
            raise ValueError(f"existing batch asset has conflicting evidence: {relative}")

    for relative, (expected_sha, expected_size) in sorted(assets.items()):
        path = existing_batch_asset(output_dir, relative)
        actual_sha, actual_size = sha256_file(path)
        if actual_sha != expected_sha or actual_size != expected_size:
            raise ValueError(f"existing batch asset content mismatch: {relative}")

    expected_files = {"manifest.json", "report.md", *assets}
    for path in output_dir.rglob("*"):
        if path.is_symlink():
            raise ValueError(f"existing batch output contains a symlink: {path.relative_to(output_dir).as_posix()}")
        if path.is_file():
            relative = path.relative_to(output_dir).as_posix()
            if relative not in expected_files:
                raise ValueError(f"existing batch output contains an unexpected file: {relative}")


def publish(args: argparse.Namespace, output_dir: Path) -> dict[str, Any]:
    output_dir = output_dir.resolve()
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    if output_dir.exists():
        result = build_manifest(args)
        manifest = result["manifest"]
        assert_existing_batch_integrity(output_dir, manifest)
        return {"manifest": manifest, "noop": True, "created": False}
    temporary = output_dir.with_name(f".{output_dir.name}.tmp-{os.getpid()}")
    if temporary.exists():
        shutil.rmtree(temporary)
    temporary.mkdir(parents=True)
    try:
        result = build_manifest(args, generated_root=temporary)
        manifest = result["manifest"]
        (temporary / "manifest.json").write_text(canonical_json(manifest) + "\n", encoding="utf-8", newline="\n")
        (temporary / "report.md").write_text(render_report(manifest), encoding="utf-8", newline="\n")
        temporary.replace(output_dir)
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise
    return {"manifest": manifest, "noop": False, "created": True}


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", required=True)
    parser.add_argument("--cold-source", required=True)
    parser.add_argument("--contracts-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--batch-id")
    parser.add_argument("--apply", action="store_true", help="write generated files; dry-run is the default")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    try:
        args = parse_args(argv)
        if args.apply:
            output = publish(args, Path(args.output_dir))
        else:
            result = build_manifest(args)
            output = {"manifest": result["manifest"], "noop": False, "created": False}
        print(canonical_json(output))
        return 0
    except Exception as error:
        print(f"prepare_batch: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
